apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: pod-ca-trust-

resources:
  - rbac.yaml
  - deployment.yaml
  - webhook.yaml
  - init.yaml

configMapGenerator:
  - name: config
    literals:
      - CA_CERT=unset

vars:
  - name: NAMESPACE
    objref:
      group: apps
      apiVersion: v1
      kind: Deployment
      name: webhook
    fieldref:
      fieldpath: metadata.namespace
  - name: SECRET_NAME
    objref:
      apiVersion: v1
      kind: Secret
      name: webhook-tls
  - name: SERVICE_NAME
    objref:
      apiVersion: v1
      kind: Service
      name: webhook
  - name: WEBHOOK_NAME
    objref:
      group: admissionregistration.k8s.io
      apiVersion: v1
      kind: MutatingWebhookConfiguration
      name: webhook.pod-ca-trust.dev

images:
  - name: webhook-image
    newName: mesosphere/pod-ca-trust
    newTag: v0.2.0
